# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4f928557106de700c3ac359a0f25f060e518297ebf888bb972d3c4e10968174b9e2a35b90ce2afb334c9bc5ab532a510700b8722d7ecc162400723cc44645e41

test:
  secret_key_base: ae3f4bbb21cf2909567072f453db2d58446964e66923bbf39295d6f0f9840a690e33c37127e2d1fb76056e3b5532031f9140edfccc135ec75a7fd11c36c41163

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
